import Header from "@/components/header";
import "./globals.css";
import Footer from "@/components/footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header className="pb-1">
         <Header />
        </header>
        <main className="mt-16">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
